[package]
name = "battle_bots_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ruscii = "0.3.2"
rand = "0.8.5"